apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::809102863946:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KLDIFZ2L9C7Y
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::809102863946:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-11T17:01:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1994"
  uid: 57ec36fd-d265-4549-8975-23e5dc1b1b38
